on:
  push:
    path-ignore:
      - 'README.md'
  pull_request:
    path-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
